(()=>{
 if(document.getElementById('gemini-bridge-v3-host'))return;
 const host=document.createElement('div');host.id='gemini-bridge-v3-host';host.style.cssText='position:fixed;right:18px;bottom:18px;z-index:2147483646;font-family:system-ui,-apple-system,Segoe UI,sans-serif';document.documentElement.appendChild(host);
 const root=host.attachShadow({mode:'closed'});
 root.innerHTML=`<style>
 :host{
   all:initial;
   --gb-surface:#fff;--gb-panel:#fff;--gb-subtle:#f7f7f8;--gb-hover:#ececec;--gb-text:#0d0d0d;--gb-muted:#6f6f6f;--gb-border:#e5e5e5;--gb-strong:#d1d1d1;--gb-danger:#b42318;--gb-danger-bg:#fff7f6;--gb-panel-shadow:0 20px 70px rgba(0,0,0,.22),0 2px 8px rgba(0,0,0,.08);--gb-composer-shadow:0 0 0 1px rgba(0,0,0,.05),0 4px 16px rgba(0,0,0,.08);--gb-focus:rgba(16,163,127,.2);--gb-focus-border:#10a37f;
 }
 *,*::before,*::after{box-sizing:border-box}.hidden{display:none!important}
 button,select,input,textarea{font:inherit;color:inherit;transition:background-color 150ms ease,border-color 150ms ease,color 150ms ease,box-shadow 150ms ease,transform 150ms ease}
 button{cursor:pointer}button:disabled{cursor:not-allowed;opacity:.46}:focus{outline:none}:focus-visible{outline:2px solid var(--gb-focus-border);outline-offset:2px}input:focus-visible,textarea:focus-visible,select:focus-visible{outline:none;border-color:var(--gb-focus-border)!important;box-shadow:0 0 0 3px var(--gb-focus)}
 .fab{border:1px solid var(--gb-border);background:var(--gb-surface);color:var(--gb-text);border-radius:999px;padding:10px 14px;box-shadow:0 8px 28px rgba(0,0,0,.14);font:600 13px/1 system-ui,-apple-system,"Segoe UI",sans-serif;cursor:pointer}.fab:hover{background:var(--gb-subtle);transform:translateY(-1px)}
 .panel{position:relative;width:min(470px,calc(100vw - 30px));height:min(760px,calc(100vh - 36px));background:var(--gb-panel);border:1px solid var(--gb-border);border-radius:18px;box-shadow:var(--gb-panel-shadow);display:none;overflow:hidden;color:var(--gb-text);font:13px/1.45 system-ui,-apple-system,"Segoe UI",sans-serif}
 .panel.open{display:grid;grid-template-rows:auto auto auto 1fr auto}
 .head{min-height:52px;padding:9px 11px 9px 14px;border-bottom:1px solid var(--gb-border);display:flex;align-items:center;gap:7px}.title{font-weight:650;letter-spacing:-.01em;flex:1}.status{font-size:10.5px;color:var(--gb-muted);max-width:130px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.icon{width:31px;height:31px;display:grid;place-items:center;border:0;background:transparent;color:var(--gb-muted);border-radius:8px;font-size:17px;cursor:pointer}.icon:hover{background:var(--gb-hover);color:var(--gb-text)}.language{height:30px;border:1px solid transparent;border-radius:8px;padding:3px 23px 3px 7px;background:transparent;color:var(--gb-muted);font:11px system-ui}.language:hover{background:var(--gb-hover);color:var(--gb-text)}
 .bar,.pendingSection{padding:10px 11px;border-bottom:1px solid var(--gb-border);display:grid;gap:7px}.bar{background:var(--gb-panel)}.row{display:flex;gap:6px;align-items:center}.grow{flex:1;min-width:0}
 .bar select,.bar button,.bar input,.settings input,.settings textarea,.footer textarea,.footer button,.pendingSection button,.newProjectDialog input,.newProjectDialog button{font:12px system-ui,-apple-system,"Segoe UI",sans-serif}.bar select,.bar input,.settings input,.settings textarea,.newProjectDialog input{border:1px solid var(--gb-border);border-radius:9px;background:var(--gb-surface);padding:7px 8px;min-width:0}.bar select:hover,.bar input:hover,.settings input:hover,.settings textarea:hover,.newProjectDialog input:hover{border-color:var(--gb-strong)}
 .bar button,.footer button,.pendingSection button,.settings button,.newProjectDialog button{min-height:32px;border:1px solid var(--gb-border);background:var(--gb-surface);border-radius:9px;padding:6px 9px;cursor:pointer}.bar button:hover,.footer button:hover,.pendingSection button:hover,.settings button:hover,.newProjectDialog button:hover{background:var(--gb-subtle);border-color:var(--gb-strong)}.primary{background:var(--gb-text)!important;color:var(--gb-surface)!important;border-color:var(--gb-text)!important;font-weight:600}.primary:hover{filter:brightness(1.08)}.danger{color:var(--gb-danger)}.bound{font-size:10.5px;color:#18764b}.warn{font-size:10.5px;color:#9a6400}.modeHelp{font-size:10.5px;color:var(--gb-muted);line-height:1.4}
 .log{padding:16px 14px;overflow:auto;background:var(--gb-panel);scrollbar-width:thin;scrollbar-color:var(--gb-strong) transparent}.empty{height:100%;display:grid;place-items:center;text-align:center;color:var(--gb-muted);font:12px/1.55 system-ui;padding:28px;box-sizing:border-box}
 .msg{margin:0 0 16px;padding:0 2px;border:0;border-radius:0;background:transparent;white-space:pre-wrap;word-break:break-word;font:13px/1.55 system-ui;color:var(--gb-text)}.msg.user{width:fit-content;max-width:84%;margin-left:auto;padding:9px 12px;border-radius:16px;background:var(--gb-subtle)}.msg.user .who{display:none}.msg.error-card{max-width:100%;padding:11px 12px;border:1px solid #efc8c4;border-radius:11px;background:var(--gb-danger-bg)}.who{font-size:10.5px;font-weight:600;color:var(--gb-muted);margin-bottom:5px}.error-title{font-weight:650;color:var(--gb-danger);margin-bottom:5px}.error-actions{margin-top:8px}.technical-details{margin-top:8px;font:10.5px system-ui;color:var(--gb-muted)}.technical-details summary{cursor:pointer;width:fit-content}.technical-details pre{white-space:pre-wrap;word-break:break-word;border:1px solid var(--gb-border);border-radius:8px;padding:8px;background:var(--gb-subtle);color:var(--gb-muted)}
 .footer{border-top:1px solid var(--gb-border);padding:10px;background:var(--gb-panel);display:grid;gap:7px}.footer textarea{resize:none;min-height:76px;max-height:180px;border:1px solid transparent;border-radius:15px;padding:11px 12px;background:var(--gb-surface);box-shadow:var(--gb-composer-shadow);color:var(--gb-text)}.footer textarea:focus{border-color:color-mix(in srgb,var(--gb-focus-border) 45%,var(--gb-border));box-shadow:var(--gb-composer-shadow),0 0 0 3px var(--gb-focus)}
 .settings{display:none;padding:11px;border-bottom:1px solid var(--gb-border);background:var(--gb-subtle);gap:7px}.settings.open{display:grid}.settings textarea{min-height:100px;resize:vertical}.pendingSection{background:#fffaf0}.pending-card{font:11px system-ui;border:1px solid #ead9a4;border-radius:9px;padding:9px}.small{font-size:10.5px;color:var(--gb-muted)}
 .newProjectDialog{position:absolute;inset:0;background:rgba(0,0,0,.34);backdrop-filter:blur(2px);z-index:4;display:grid;place-items:center}.dialog-card{width:min(330px,calc(100% - 34px));box-sizing:border-box;background:var(--gb-surface);color:var(--gb-text);border:1px solid var(--gb-border);border-radius:16px;padding:17px;box-shadow:var(--gb-panel-shadow);display:grid;gap:10px}.dialog-title{font:650 15px system-ui}.dialog-lead{font:11px/1.45 system-ui;color:var(--gb-muted)}
 @media(prefers-color-scheme:dark){:host{--gb-surface:#2f2f2f;--gb-panel:#212121;--gb-subtle:#303030;--gb-hover:#353535;--gb-text:#ececec;--gb-muted:#b4b4b4;--gb-border:#3c3c3c;--gb-strong:#505050;--gb-danger:#ff8b84;--gb-danger-bg:#3a2424;--gb-panel-shadow:0 22px 80px rgba(0,0,0,.46),0 2px 8px rgba(0,0,0,.34);--gb-composer-shadow:0 0 0 1px rgba(255,255,255,.06),0 8px 24px rgba(0,0,0,.25)}.primary{background:#ececec!important;color:#171717!important;border-color:#ececec!important}.pendingSection{background:#342f20}.msg.error-card{border-color:#6a3734}.bound{color:#69d69d}.warn{color:#e7b65c}}
 @media(max-width:560px){.panel{width:calc(100vw - 20px);height:calc(100vh - 20px);border-radius:15px}.status{display:none}.head{padding-left:11px}.bar{padding:9px}.log{padding:12px 10px}.footer{padding:8px}}
 @media(prefers-reduced-motion:reduce){*,*::before,*::after{transition-duration:.01ms!important;animation-duration:.01ms!important;animation-iteration-count:1!important}}
 </style>
 <button class="fab">◆ Gemini</button><section class="panel">
 <div class="head"><span class="title">◆ Gemini Bridge</span><span class="status">local</span><select class="language" aria-label="Language"><option value="ru">RU</option><option value="en">EN</option></select><button class="icon settingsBtn" title="Project settings">⚙</button><button class="icon close">×</button></div>
 <div class="bar"><div class="row"><select class="project grow"></select><button class="newp"></button><button class="bind"></button></div><div class="row"><span class="binding warn grow"></span></div><div class="threadSection hidden"><div class="row"><select class="thread grow"></select><button class="newt"></button></div></div><div class="row"><select class="mode grow"><option value="ask"></option><option value="review"></option><option value="edit"></option></select></div><div class="modeHelp"></div></div>
 <div class="settings"><input class="pname"><input class="workspace"><textarea class="context"></textarea><div class="row"><button class="saveSettings primary"></button><button class="hideSettings"></button></div><div class="small snapshotHint"></div></div>
 <div class="pendingSection hidden"><div class="pendingTitle small"></div><div class="pending"></div></div><div class="log"></div>
 <div class="footer"><textarea class="prompt"></textarea><div class="row"><button class="handoff"></button><button class="cancel hidden"></button><span class="grow"></span><button class="send primary" disabled></button></div></div>
 <div class="newProjectDialog hidden"><form class="dialog-card"><div class="dialog-title"></div><div class="dialog-lead"></div><input class="newProjectName" maxlength="120"><div class="row"><span class="grow"></span><button type="button" class="cancelProject"></button><button type="submit" class="createProject primary"></button></div></form></div>
 </section>`;
 const $=s=>root.querySelector(s),fab=$('.fab'),panel=$('.panel'),status=$('.status'),project=$('.project'),thread=$('.thread'),mode=$('.mode'),binding=$('.binding'),log=$('.log'),prompt=$('.prompt'),send=$('.send'),cancel=$('.cancel'),pending=$('.pending'),pendingSection=$('.pendingSection'),threadSection=$('.threadSection'),settings=$('.settings'),language=$('.language'),newProjectDialog=$('.newProjectDialog');
 let currentRun=null,pollTimer=null,pollInFlight=false,pollGeneration=0,lastRoute=location.pathname+location.search,pendingSubmission=null;
 const browserLanguage=String((navigator.languages&&navigator.languages[0])||navigator.language||'en').toLowerCase();
 let lang=browserLanguage.startsWith('ru')?'ru':'en';

 const I18N={
  ru:{useHere:'Использовать здесь',notBound:'Эта страница ChatGPT пока не связана с проектом Bridge.',chooseBind:'Выбери проект Bridge и нажми «Использовать здесь».',bound:'Этот диалог ChatGPT использует выбранный проект Bridge.',switchBind:'Нажми «Использовать здесь», чтобы переключить этот диалог ChatGPT на выбранный проект.',newProject:'Новый проект',newThread:'Новый диалог',modeAsk:'Спросить',modeReview:'Анализ проекта',modeEdit:'Изменить файлы',askHelp:'Обычный разговор с Gemini. Файлы проекта не используются.',reviewHelp:'Gemini читает безопасную копию папки проекта, но ничего в ней не изменяет.',editHelp:'Gemini меняет только отдельную копию. Перед применением ты увидишь предпросмотр.',projectName:'Название проекта',workspace:'Папка проекта (для анализа/изменений)',context:'Контекст проекта / handoff из ChatGPT',save:'Сохранить',close:'Закрыть',snapshot:'Для анализа и изменений Gemini получает только безопасную копию проекта.',pending:'Неприменённые изменения',message:'Напиши Gemini…',copyHandoff:'Скопировать контекст',cancel:'Отменить',send:'Отправить',empty:'Можно задать вопрос Gemini или выбрать проект и продолжить существующий диалог.',dialogLead:'Название можно изменить позже. Папка проекта настраивается отдельно.',create:'Создать',projectCreated:'Проект создан. Нажми «Использовать здесь», чтобы связать его с этим диалогом ChatGPT.',connected:'Bridge подключён',selected:'Проект выбран для этого диалога ChatGPT',projectSaved:'Проект сохранён',handoffCopied:'Контекст скопирован',handoffManual:'Контекст показан для ручного копирования',clipboardBlocked:'Браузер запретил доступ к буферу. Скопируй контекст вручную:',you:'ВЫ',gemini:'◆ GEMINI',resumed:'◆ GEMINI · продолжение',resuming:'Продолжаем незавершённый запрос…',starting:'Запуск…',cancelling:'Отменяем…',failedTitle:'Не удалось получить ответ Gemini',cancelledTitle:'Запрос отменён',retry:'Повторить',technical:'Технические подробности',preview:'Предпросмотр',apply:'Применить',reconcile:'Согласовать',discard:'Отменить изменения',discardConfirm:'Удалить локальную копию изменений агента? Уже применённые файлы это не откатит.',workspaceRequired:'Для анализа проекта и изменения файлов нужна локальная папка. Открой «Настройки проекта» и выбери папку.',settingsTitle:'Настройки проекта',noProjectName:'Введи название проекта.'},
  en:{useHere:'Use here',notBound:'This ChatGPT page is not bound.',chooseBind:'Choose a Bridge project, then click Use here for this ChatGPT conversation.',bound:'This ChatGPT conversation uses this Bridge project',switchBind:'Click Use here to switch this ChatGPT conversation to the selected Bridge project.',newProject:'New project',newThread:'New thread',modeAsk:'Ask',modeReview:'Project review',modeEdit:'Edit files',askHelp:'A normal Gemini conversation. Project files are not used.',reviewHelp:'Gemini reads a sanitized copy of the selected folder but cannot change it.',editHelp:'Gemini edits only a separate copy. Preview the changes before applying them.',projectName:'Project name',workspace:'Local workspace path (Review/Agent)',context:'Project context / ChatGPT handoff',save:'Save',close:'Close',snapshot:'Only sanitized snapshot files are sent to Gemini in Review/Agent modes.',pending:'Pending Agent work',message:'Message Gemini…',copyHandoff:'Copy handoff',cancel:'Cancel',send:'Send to Gemini',empty:'Ask Gemini a question, or select a project and continue an existing thread.',dialogLead:'You can rename it later and connect the project folder separately.',create:'Create',projectCreated:'Project created. Click Use here to use it in this ChatGPT conversation.',connected:'Connected to local Bridge',selected:'Project selected for this ChatGPT conversation',projectSaved:'Project saved',handoffCopied:'Handoff copied',handoffManual:'Handoff shown for manual copy',clipboardBlocked:'Clipboard access was blocked. Copy the handoff manually:',you:'YOU',gemini:'◆ GEMINI',resumed:'◆ GEMINI · resumed',resuming:'Resuming this active Gemini run…',starting:'Starting…',cancelling:'Cancelling…',failedTitle:'Could not get a Gemini response',cancelledTitle:'Request cancelled',retry:'Retry',technical:'Technical details',preview:'Preview',apply:'Apply',reconcile:'Reconcile',discard:'Discard',discardConfirm:'Discard this local Agent snapshot? This does not roll back files already applied.',workspaceRequired:'Review and Agent Edit need a local workspace. Open Project settings and choose the project folder first.',settingsTitle:'Project settings',noProjectName:'Enter a project name.'}
 };
 const t=k=>I18N[lang]?.[k]??I18N.en[k]??k;
 const modeHelp=()=>({ask:t('askHelp'),review:t('reviewHelp'),edit:t('editHelp')})[mode.value]||'';

 const routeKey=()=>`${location.origin}${location.pathname}${location.search}`;
 const message=(payload)=>new Promise((resolve,reject)=>chrome.runtime.sendMessage(payload,r=>{if(chrome.runtime.lastError)reject(new Error(chrome.runtime.lastError.message));else if(!r?.ok)reject(new Error(r?.error||'Bridge unavailable'));else resolve(r.data);}));
 const api=(path,options={})=>message({kind:'gb-api',path,options});
 const bindingGet=()=>message({kind:'gb-binding-get',route:routeKey()});
 const bindingSet=value=>message({kind:'gb-binding-set',route:routeKey(),value});
 const prefGet=key=>message({kind:'gb-pref-get',key});
 const prefSet=(key,value)=>message({kind:'gb-pref-set',key,value});

 function applyI18n(){
   language.value=lang;$('.newp').textContent=`+ ${t('newProject')}`;$('.bind').textContent=t('useHere');$('.newt').textContent=t('newThread');
   mode.querySelector('[value="ask"]').textContent=t('modeAsk');mode.querySelector('[value="review"]').textContent=t('modeReview');mode.querySelector('[value="edit"]').textContent=t('modeEdit');$('.modeHelp').textContent=modeHelp();
   $('.settingsBtn').title=t('settingsTitle');$('.pname').placeholder=t('projectName');$('.workspace').placeholder=t('workspace');$('.context').placeholder=t('context');$('.saveSettings').textContent=t('save');$('.hideSettings').textContent=t('close');$('.snapshotHint').textContent=t('snapshot');$('.pendingTitle').textContent=t('pending');
   prompt.placeholder=t('message');$('.handoff').textContent=t('copyHandoff');cancel.textContent=t('cancel');send.textContent=t('send');$('.dialog-title').textContent=t('newProject');$('.dialog-lead').textContent=t('dialogLead');$('.newProjectName').placeholder=t('projectName');$('.cancelProject').textContent=t('close');$('.createProject').textContent=t('create');
 }
 async function setLanguage(next,{persist=true,rerender=true}={}){lang=next==='ru'?'ru':'en';applyI18n();if(persist)try{await prefSet('language',lang);}catch{}if(rerender){if(thread.value)await loadConversation();if(project.value)await loadPending();}}
 async function loadLanguagePreference(){try{const saved=await prefGet('language');if(saved==='ru'||saved==='en')lang=saved;}catch{}applyI18n();}

 function errorInfo(raw){
   const text=String(raw?.message||raw||'Unknown error'),code=text.split(':')[0].trim(),low=text.toLowerCase();let key='provider';
   if(code==='WORKSPACE_BUSY')return {kind:'workspace',message:lang==='ru'?'Эта папка занята другой операцией. Дождись её завершения или используй «Спросить» в другом диалоге.':'This workspace is busy with another Review or Agent Edit. Ask still works in another Gemini thread; otherwise wait for the workspace operation to finish.',technical:text};
   if(code==='THREAD_BUSY')return {kind:'thread',message:lang==='ru'?'В этом диалоге уже выполняется запрос. Дождись его завершения или отмени его.':'This Gemini thread already has a run in progress. Wait for it to finish or cancel it, then try again.',technical:text};
   if(code==='PENDING_AGENT_CHANGES')return {kind:'pending',message:lang==='ru'?'В проекте есть неприменённые изменения. Сначала просмотри, примени, согласуй или отмени их.':'This workspace has pending Agent changes. Preview and Apply, Reconcile, or Discard them before starting another Review/Agent Edit.',technical:text};
   if(code==='HOST_MAINTENANCE')return {kind:'maintenance',message:lang==='ru'?'Gemini Bridge обслуживается или завершает работу. Дождись окончания Setup/Repair.':'Gemini Bridge is in maintenance or shutting down. Wait for Setup/Repair to finish, then try again.',technical:text};
   if(code==='WORKSPACE_REQUIRED')return {kind:'workspace',message:t('workspaceRequired'),technical:text};
   if(code==='GEMINI_BUSY')return {kind:'busy',message:lang==='ru'?'Сейчас заняты все процессы Gemini. Дождись завершения одного запроса.':'Gemini Bridge is already using all available Gemini process slots. Wait for one run to finish.',technical:text};
   if(code==='PAIRING_REQUIRED')return {kind:'pairing',message:lang==='ru'?'Связь расширения с Gemini Bridge устарела. Запусти Setup/Repair и нажми «Обновить» у расширения.':'Pairing changed. Run Gemini Bridge Setup/Repair and Reload this unpacked extension.',technical:text};
   if(code==='BRIDGE_TIMEOUT')return {kind:'timeout',message:lang==='ru'?'Локальный Host не ответил вовремя. Проверь, что Gemini Bridge запущен.':'The local Gemini Bridge Host did not respond in time. Check that Gemini Bridge is running.',technical:text};
   if(/oauth|auth|google|credential|login|sign.?in/.test(low))key='auth';else if(/quota|rate|429|resource_exhausted/.test(low))key='quota';else if(/network|econn|etimedout|enotfound|fetch/.test(low))key='network';else if(/gemini_cli_not_available/.test(low))key='runtime';else if(/gemini_protocol|gemini_result_error/.test(low))key='protocol';
   const ru={auth:'Gemini не смог использовать аккаунт Google. Повтори вход и затем повтори запрос.',quota:'Gemini временно ограничил запросы или исчерпана квота. Подожди и повтори.',network:'Bridge не смог связаться с провайдером. Проверь интернет и повтори.',runtime:'Локальный Gemini runtime недоступен. Запусти Setup/Repair.',protocol:'Gemini вернул данные, которые Bridge не может безопасно обработать. Повтори один раз; при повторе сохрани подробности.',provider:'Gemini не завершил запрос. Сообщение сохранено — его можно повторить или раскрыть технические подробности.'};
   const en={auth:'Gemini could not use the Google account. Sign in again, then retry.',quota:'Gemini is temporarily rate-limited or the current quota is exhausted. Wait a little and retry.',network:'Gemini Bridge could not reach the provider. Check the internet connection and retry.',runtime:'The managed Gemini runtime is not available. Run Gemini Bridge Setup/Repair.',protocol:'Gemini returned data that Bridge could not safely interpret. Retry once; if it repeats, keep the technical details.',provider:'Gemini did not complete this request. The message was kept, so you can retry it or inspect the technical details.'};
   return {kind,message:(lang==='ru'?ru:en)[key],technical:text};
 }
 function friendlyError(raw){return errorInfo(raw).message;}
 function runLabel(s){const ru={QUEUED:'Запуск…',RUNNING:'Gemini отвечает…',COMPLETED:'Готово',WAITING_APPLY:'Изменения готовы к просмотру',RECOVERY_REQUIRED:'Доступно восстановление',APPLYING:'Применяем…',APPLIED:'Применено',APPLY_CONFLICT:'Обнаружены внешние изменения',APPLY_RECOVERY_REQUIRED:'Нужно восстановление применения',DISCARDED:'Отменено',FAILED:'Ошибка',CANCELLED:'Отменено пользователем'},en={QUEUED:'Starting…',RUNNING:'Gemini is working…',COMPLETED:'Completed',WAITING_APPLY:'Ready to preview and apply',RECOVERY_REQUIRED:'Recovery is available',APPLYING:'Applying safely…',APPLIED:'Applied',APPLY_CONFLICT:'External change detected',APPLY_RECOVERY_REQUIRED:'Apply needs recovery',DISCARDED:'Discarded',FAILED:'Failed',CANCELLED:'Cancelled'};return (lang==='ru'?ru:en)[s]||String(s||'');}
 function managementOutcome(action,out){const s=out?.run?.status||out?.status||'';if(lang==='en'){if(s==='APPLY_CONFLICT')return 'External changes were detected. The conflicting file was left unchanged; nothing was overwritten at the conflict. Review Preview and choose Reconcile after deciding which version should win.';if(action==='apply'&&s==='APPLIED')return 'Changes were applied to the live workspace.';if(action==='reconcile'&&s==='APPLIED')return 'Reconcile confirmed the safe result and the changes are applied to the live workspace.';if(action==='reconcile'&&s==='WAITING_APPLY')return 'Reconcile verified the workspace. The remaining changes are safe to Preview and Apply.';if(action==='discard'||s==='DISCARDED')return 'The Agent snapshot was discarded. Live workspace files already applied, if any, are not rolled back.';}else{if(s==='APPLY_CONFLICT')return 'Обнаружены внешние изменения. Конфликтующий файл не перезаписан; выбери нужную версию и используй «Согласовать».';if(action==='apply'&&s==='APPLIED')return 'Изменения применены к рабочей папке.';if(action==='reconcile'&&s==='APPLIED')return 'Согласование подтвердило безопасный результат — изменения применены.';if(action==='reconcile'&&s==='WAITING_APPLY')return 'Рабочая папка проверена. Оставшиеся изменения можно просмотреть и применить.';if(action==='discard'||s==='DISCARDED')return 'Локальная копия изменений удалена. Уже применённые файлы автоматически не откатываются.';}return runLabel(s)||(lang==='ru'?'Операция завершена.':'Operation completed.');}
 const setStatus=x=>status.textContent=x;
 async function copyOrFallback(text){try{await navigator.clipboard.writeText(text);setStatus(t('handoffCopied'));}catch{window.prompt(t('clipboardBlocked'),text);setStatus(t('handoffManual'));}}
 function addMsg(who,text,user=false){const d=document.createElement('div');d.className='msg'+(user?' user':'');const h=document.createElement('div');h.className='who';h.textContent=who;const b=document.createElement('div');b.textContent=text||'';d.append(h,b);log.append(d);log.scrollTop=log.scrollHeight;return b;}
 function renderEmpty(){if(log.children.length)return;const e=document.createElement('div');e.className='empty';e.textContent=t('empty');log.append(e);}
 function renderFailed(x){addMsg(t('you'),x.prompt||'',true);const info=errorInfo(x.error||x.status||'FAILED');const d=document.createElement('div');d.className='msg error-card';const h=document.createElement('div');h.className='who';h.textContent='GEMINI BRIDGE';const title=document.createElement('div');title.className='error-title';title.textContent=x.status==='CANCELLED'?t('cancelledTitle'):t('failedTitle');const body=document.createElement('div');body.textContent=info.message;const actions=document.createElement('div');actions.className='row error-actions';const retry=document.createElement('button');retry.textContent=t('retry');retry.onclick=()=>retryFailedRun(x);actions.append(retry);const details=document.createElement('details');details.className='technical-details';const summary=document.createElement('summary');summary.textContent=t('technical');const pre=document.createElement('pre');pre.textContent=info.technical;details.append(summary,pre);d.append(h,title,body,actions,details);log.append(d);log.scrollTop=log.scrollHeight;}

 async function ensureStarterBinding(projects){if(projects.length===0){const made=await api('/v1/projects',{method:'POST',body:{name:'My project'}});projects=[made.project];if(projects.length===1)await bindingSet({projectId:projects[0].id,threadId:null});}return projects;}
 async function loadProjects(){const r=await api('/v1/projects');let projects=await ensureStarterBinding(r.projects||[]);const old=project.value;project.textContent='';for(const p of projects){const o=document.createElement('option');o.value=p.id;o.textContent=p.name;project.append(o);}if(old&&[...project.options].some(o=>o.value===old))project.value=old;await loadBinding();}
 async function loadBinding(){const b=await bindingGet();if(b?.projectId&&[...project.options].some(o=>o.value===b.projectId)){project.value=b.projectId;binding.textContent=t('bound');binding.className='binding bound';send.disabled=false;await loadThreads(b.threadId||null);await loadSettingsFields();await loadPending();}else{binding.textContent=t('chooseBind');binding.className='binding warn';send.disabled=true;thread.textContent='';threadSection.classList.add('hidden');log.textContent='';renderEmpty();pending.textContent='';pendingSection.classList.add('hidden');}}
 async function loadThreads(preferred=null){if(!project.value)return;const r=await api(`/v1/projects/${encodeURIComponent(project.value)}/threads`);thread.textContent='';for(const th of r.threads||[]){const o=document.createElement('option');o.value=th.id;o.textContent=th.title;thread.append(o);}if(preferred&&[...thread.options].some(o=>o.value===preferred))thread.value=preferred;threadSection.classList.toggle('hidden',thread.options.length===0);if(thread.value)await loadConversation();else{log.textContent='';renderEmpty();}}
 async function loadConversation(){log.textContent='';if(!thread.value){renderEmpty();return;}const r=await api(`/v1/threads/${encodeURIComponent(thread.value)}/conversation?limit=100`);for(const item of r.items||[]){if(item.kind==='message')addMsg(item.role==='user'?t('you'):t('gemini'),item.content,item.role==='user');else if(item.kind==='failed-run')renderFailed(item);}renderEmpty();}
 async function loadSettingsFields(){const r=await api('/v1/projects');const p=r.projects.find(x=>x.id===project.value);if(!p)return null;$('.pname').value=p.name||'';$('.workspace').value=p.workspace||'';$('.context').value=p.context||'';return p;}
 async function preflightWorkspace(selectedMode=mode.value){if(selectedMode==='ask')return true;const p=await loadSettingsFields();if(p?.workspace)return true;settings.classList.add('open');setStatus(friendlyError('WORKSPACE_REQUIRED'));return false;}

 async function performManagement(x,action){try{const out=await api(`/v1/runs/${x.id}/${action}`,{method:'POST',body:{}});setStatus(managementOutcome(action,out));await loadPending();await loadConversation();}catch(e){setStatus(friendlyError(e));}}
 async function loadPending(){if(!project.value){pendingSection.classList.add('hidden');return;}const r=await api(`/v1/projects/${encodeURIComponent(project.value)}/pending`);pending.textContent='';const runs=r.runs||[];pendingSection.classList.toggle('hidden',runs.length===0);const active=runs.find(x=>['QUEUED','RUNNING'].includes(x.status));for(const x of runs){const d=document.createElement('div');d.className='pending-card';const txt=document.createElement('div');txt.textContent=`${x.mode} · ${runLabel(x.status)}`;d.append(txt);if(x.error){const er=document.createElement('div');er.className='small';er.textContent=friendlyError(x.error);d.append(er);}if(x.recoveryPid){const note=document.createElement('div');note.className='small';note.textContent=lang==='ru'?`Bridge подтвердил, что предыдущий процесс Gemini (PID ${x.recoveryPid}) всё ещё жив. Дождись его завершения; не завершай процесс только по PID.`:`Bridge verified that its previous Gemini process (PID ${x.recoveryPid}) is still alive. Wait for it to exit; do not terminate a process based on PID alone.`;d.append(note);}if(x.result?.diffSummary){const sm=document.createElement('pre');sm.className='diff';sm.textContent=x.result.diffSummary;d.append(sm);}const row=document.createElement('div');row.className='row';if(['WAITING_APPLY','RECOVERY_REQUIRED','APPLY_CONFLICT','APPLY_RECOVERY_REQUIRED'].includes(x.status)){const pv=document.createElement('button');pv.textContent=t('preview');pv.onclick=async()=>{try{const out=await api(`/v1/runs/${x.id}/preview`);let pre=d.querySelector('.fullpreview');if(!pre){pre=document.createElement('pre');pre.className='diff fullpreview';d.append(pre);}pre.textContent=out.preview.items.map(i=>`### ${i.type.toUpperCase()} ${i.path} · ${i.state}\n--- BEFORE ---\n${i.before??'(missing)'}\n--- AFTER ---\n${i.after??'(deleted)'}`).join('\n\n');}catch(e){setStatus(friendlyError(e));}};row.append(pv);const action=x.status==='WAITING_APPLY'?'apply':'reconcile';const a=document.createElement('button');a.textContent=action==='apply'?t('apply'):t('reconcile');a.onclick=()=>performManagement(x,action);row.append(a);if(['WAITING_APPLY','RECOVERY_REQUIRED','APPLY_CONFLICT'].includes(x.status)){const ds=document.createElement('button');ds.textContent=t('discard');ds.className='danger';ds.onclick=async()=>{if(!confirm(t('discardConfirm')))return;await performManagement(x,'discard');};row.append(ds);}}d.append(row);pending.append(d);}if(active&&!currentRun)pollRun(active.id,true);}

 function pollRun(id,resume=false){clearInterval(pollTimer);const generation=++pollGeneration;currentRun=id;cancel.classList.remove('hidden');send.disabled=true;const box=addMsg(resume?t('resumed'):t('gemini'),resume?t('resuming'):t('starting'));const tick=async()=>{if(pollInFlight||generation!==pollGeneration)return;pollInFlight=true;try{const r=(await api(`/v1/runs/${id}`)).run;if(generation!==pollGeneration)return;box.textContent=r.partialText||r.resultText||(r.error?friendlyError(r.error):runLabel(r.status));setStatus(runLabel(r.status));if(!['QUEUED','RUNNING'].includes(r.status)){clearInterval(pollTimer);pollTimer=null;currentRun=null;cancel.classList.add('hidden');send.disabled=false;await loadThreads(r.threadId);await loadPending();}}catch(e){if(generation===pollGeneration)setStatus(friendlyError(e));}finally{pollInFlight=false;}};tick();pollTimer=setInterval(tick,450);}
 async function doSend({promptText=null,selectedMode=null,threadIdOverride=undefined}={}){if(send.disabled||!project.value)return;send.disabled=true;const route=routeKey();let bound;try{bound=await bindingGet();}catch(e){setStatus(friendlyError(e));send.disabled=false;return;}if(!bound||bound.projectId!==project.value){setStatus(t('chooseBind'));send.disabled=false;return;}const q=String(promptText===null?prompt.value:promptText).trim();if(!q){send.disabled=false;return;}const chosenMode=selectedMode||mode.value;if(!await preflightWorkspace(chosenMode)){send.disabled=false;return;}const tid=threadIdOverride===undefined?(thread.value||bound.threadId||null):threadIdOverride;const submissionKey=JSON.stringify([project.value,tid,chosenMode,q,route]);if(!pendingSubmission||pendingSubmission.key!==submissionKey)pendingSubmission={key:submissionKey,requestId:crypto.randomUUID()};const requestId=pendingSubmission.requestId;try{const r=await api('/v1/runs',{method:'POST',body:{projectId:project.value,threadId:tid,mode:chosenMode,prompt:q,requestId}});pendingSubmission=null;if(route!==routeKey()){setStatus(lang==='ru'?'Диалог ChatGPT изменился во время запуска. Открой панель в текущем диалоге и снова нажми «Использовать здесь».':'ChatGPT conversation changed while the run was starting. Open the panel on the current conversation and choose Use here before sending again.');send.disabled=false;return;}prompt.value='';addMsg(t('you'),q,true);await bindingSet({projectId:project.value,threadId:r.run.threadId});await loadThreads(r.run.threadId);pollRun(r.run.id);}catch(e){setStatus(friendlyError(e));send.disabled=false;}}
 async function retryFailedRun(x){if(x.projectId&&project.value!==x.projectId){project.value=x.projectId;await loadThreads(x.threadId||null);}else if(x.threadId&&thread.value!==x.threadId){await loadThreads(x.threadId);}mode.value=x.mode||'ask';$('.modeHelp').textContent=modeHelp();prompt.value=x.prompt||'';prompt.focus();await doSend({promptText:x.prompt||'',selectedMode:x.mode||'ask',threadIdOverride:x.threadId||null});}

 fab.onclick=async()=>{panel.classList.add('open');fab.style.display='none';try{await loadLanguagePreference();await loadProjects();setStatus(t('connected'));}catch(e){setStatus(friendlyError(e));}};
 $('.close').onclick=()=>{panel.classList.remove('open');fab.style.display='';};$('.settingsBtn').onclick=()=>settings.classList.toggle('open');$('.hideSettings').onclick=()=>settings.classList.remove('open');
 $('.newp').onclick=()=>{newProjectDialog.classList.remove('hidden');$('.newProjectName').value='';setTimeout(()=>$('.newProjectName').focus(),0);};$('.cancelProject').onclick=()=>newProjectDialog.classList.add('hidden');$('.dialog-card').onsubmit=async e=>{e.preventDefault();const name=$('.newProjectName').value.trim();if(!name){setStatus(t('noProjectName'));return;}try{const r=await api('/v1/projects',{method:'POST',body:{name}});newProjectDialog.classList.add('hidden');await loadProjects();project.value=r.project.id;send.disabled=true;binding.textContent=t('projectCreated');setStatus(t('projectCreated'));}catch(err){setStatus(friendlyError(err));}};
 $('.bind').onclick=async()=>{if(!project.value)return;await bindingSet({projectId:project.value,threadId:thread.value||null});await loadBinding();setStatus(t('selected'));};
 project.onchange=async()=>{send.disabled=true;binding.textContent=t('switchBind');await loadThreads();await loadSettingsFields();await loadPending();};thread.onchange=async()=>{const b=await bindingGet();if(b?.projectId===project.value)await bindingSet({projectId:project.value,threadId:thread.value||null});await loadConversation();};
 $('.newt').onclick=async()=>{if(!project.value)return;try{const r=await api(`/v1/projects/${project.value}/threads`,{method:'POST',body:{title:t('newThread')}});await loadThreads(r.thread.id);const b=await bindingGet();if(b?.projectId===project.value)await bindingSet({projectId:project.value,threadId:r.thread.id});}catch(e){setStatus(friendlyError(e));}};
 $('.saveSettings').onclick=async()=>{try{await api(`/v1/projects/${project.value}`,{method:'PATCH',body:{name:$('.pname').value,workspace:$('.workspace').value,context:$('.context').value}});settings.classList.remove('open');await loadProjects();setStatus(t('projectSaved'));}catch(e){setStatus(friendlyError(e));}};
 $('.handoff').onclick=async()=>{try{const r=await api('/v1/handoff',{method:'POST',body:{projectId:project.value,threadId:thread.value||null}});await copyOrFallback(r.text);}catch(e){setStatus(friendlyError(e));}};
 send.onclick=()=>doSend();prompt.addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();doSend();}});cancel.onclick=async()=>{if(!currentRun)return;try{await api(`/v1/runs/${currentRun}/cancel`,{method:'POST',body:{}});setStatus(t('cancelling'));}catch(e){setStatus(friendlyError(e));}};mode.onchange=()=>$('.modeHelp').textContent=modeHelp();language.onchange=()=>setLanguage(language.value);
 setInterval(async()=>{const route=location.pathname+location.search;if(route!==lastRoute){lastRoute=route;++pollGeneration;clearInterval(pollTimer);pollTimer=null;currentRun=null;send.disabled=true;try{await loadBinding();}catch(e){setStatus(friendlyError(e));}}},500);
 applyI18n();renderEmpty();loadLanguagePreference().catch(()=>{});
})();
